version: '3.8'

services:
  backend:
    build:
      context: ./spring-app
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "35729:35729" # LiveReload port
      - "5005:5005" # Remote debug port
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    volumes:
      - ./spring-app/src:/app/src
      - ./spring-app/target:/app/target
      - maven-repo:/root/.m2

  frontend:
    build:
      context: ./angular-app
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200" # Angular dev server port
    volumes:
      - ./angular-app/src:/app/src
      - ./angular-app/public:/app/public
      - ./angular-app/node_modules:/app/node_modules
    depends_on:
      - backend

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  maven-repo:
