version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./spring-app
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080" # Application port
      - "35729:35729" # LiveReload port
      - "5005:5005" # Remote debug port
    volumes:
      - ./spring-app:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./angular-app
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200" # Angular dev server port
    volumes:
      - ./angular-app/src:/app/src
      - ./angular-app/public:/app/public
    depends_on:
      - backend

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  maven-repo:
