version: '3.8'

services:  
  backend:
    build:
      context: ./spring-app
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "35729:35729" # LiveReload port
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    volumes:
      - ./spring-app/src:/app/src
      - ./spring-app/target:/app/target
  frontend:
    build:
      context: ./angular-app
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200" # Angular dev server port
    volumes:
      - ./angular-app/src:/app/src
      - ./angular-app/public:/app/public
    depends_on:
      - backend
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
